src/renderer.tsx
Already deprecated and will be removed in 4.0.0-rc.1: https://github.com/lensapp/lens/pull/1505
=> Remove routePath

CHANGELOG.md, package.json, src/cc/store/ExtStateProvider.js, src/page.tsx
Relies on https://github.com/lensapp/lens/pull/1785 to work, which is in Lens 4.0.4.
Lens now generates data directories for extensions that are safe,
even if the extension gets uninstalled. This commit uses that
generated directory as the new default save path.
=> Default save path pref to safe directory

CHANGELOG.md, src/cc/ClusterList.js, src/cc/View.js, src/cc/store/Cluster.js, src/cc/store/ClustersProvider.js, src/strings.ts
Fixes #95
The list of clusters to add will now omit any clusters being deleted,
and will show, but not allow to be selected, clusters that are still
being provisioned. Those will also have a "(not ready)" label on them.
=> Prevent non-ready and deleted clusters from being added

src/page.tsx
Lens is using architecture when multiple emotion instances can be activated. Currently, all of them shares same `<style>` tag causing dropping all of the styles inside of it. Original bug: https://github.com/lensapp/lens/issues/2219.
This PR wraps all `emotion` contents into `<CacheProvider/>` which helps to isolate MCC Extension styles and prevents other emotion styles to be removed.
Part of https://github.com/lensapp/lens/pull/2365
Signed-off-by: Alex Andreev <alex.andreev.email@gmail.com>
=> Wrapping emotion instance into CacheProvider

src/renderer/auth/Cloud.js
After #622, we weren't serializing the new property to JSON, so
it was undefined when cloning the Cloud object.
=> [PRODX-19642] Fix crash on load from missing cloudUrl

src/renderer/components/CloseButton/CloseButton.js, src/renderer/components/GlobalPage/AddCloudInstance.js, src/renderer/components/GlobalPage/ConnectionBlock.js, src/renderer/components/GlobalPage/SyncView.js, src/renderer/components/GlobalPage/SynchronizeBlock.js, src/strings.ts
To go to new page do `shift+click` on SyncPage title. 
this is just a mockup. All other logic and connection with other parts will be added in the future tickets
=> [PRODX-20593] Add new MCC Connection page

src/renderer/components/GlobalPage/ConnectionBlock.js, src/renderer/eventBus.ts, src/renderer/renderer.tsx, src/store/CloudStore.js
Now we can store Cloud instances directly inside CloudStore.clouds.
I also fixed an issue with passing the data to the OAuth event:
We shouldn't remove `state` from the data when dispatching
the event so that the data payload remains intact for any
handlers.
=> Fix CloudStore serialization of clouds property

CHANGELOG.md, src/renderer/components/GlobalPage/ClusterList.js, src/renderer/eventBus.ts, src/renderer/renderer.tsx, src/renderer/store/Cluster.js, src/renderer/store/ClusterActionsProvider.js, src/renderer/store/ClusterDataProvider.js, src/util/templates.js
When manually adding a cluster from MCC into Lens via downloaded
kubeconfig, Lens generates its own UID for the cluster since the
UID isn't given in the kubeconfig. That means we can't search
by UID when opening a cluster from MCC in the browser that
wasn't added via the extension.
This changes to searching by the same context name that MCC generates
in its kubeconfigs. So now we can find any cluster, whether it was
manually added, or added via the extension.
Note, however, we still fall back to using the cluster UID if we
don't get a username in the "activate cluster" event, as that
would be triggered by an older version of MCC that doesn't have
the fix to send over the username.
=> Enable opening clusters in Lens based on context instead of UID

CHANGELOG.md, src/common/Cloud.js, src/constants.js, src/renderer/auth/clients/AuthClient.js, src/renderer/components/GlobalPage/ClusterList.js, src/renderer/components/GlobalPage/SyncView.js, src/renderer/eventBus.ts, src/renderer/renderer.tsx, src/renderer/store/Cluster.js, src/renderer/store/ClusterActionsProvider.js, src/renderer/store/ClusterDataProvider.js, src/util/templates.js
When manually adding a cluster from MCC into Lens via downloaded
kubeconfig, Lens generates its own UID for the cluster since the
UID isn't given in the kubeconfig. That means we can't search
by UID when opening a cluster from MCC in the browser that
wasn't added via the extension.
This changes to searching by the same context name that MCC generates
in its kubeconfigs. So now we can find any cluster, whether it was
manually added, or added via the extension.
=> [PRODX-21176] Enable opening clusters in Lens based on context

CHANGELOG.md, src/common/Cloud.js, src/strings.ts, src/util/netUtil.js, src/util/ssoUtil.js
This addresses CVE-2022-0484 where `openExternal()` provided by
Lens is designed to open _anything_, which means even `file:` protocols
that would result in local code execution (if MCC URL is spoofed and has
a config.js that provides a `file:` URL for Keycloak, for example).
NOTE: This ports commit 23330ad9181022157ee51fedbdfb4d45b848cf49 on
`v3-maint` branch to `master`.
=> Fix CVE-2022-0484

src/common/Cloud.js, src/common/ExtendedCloud.js, src/renderer/auth/authUtil.js, src/renderer/components/GlobalPage/AddCloudInstance.js, src/renderer/store/ExtendedCloudProvider.js, src/store/CloudStore.js, src/store/ClusterStore.js, src/strings.ts, src/util/ssoUtil.js, test/mocks/mockExtCloud.js
There was too much churn when fetching data for an ExtendedCloud:
Duplicated requests, multiple parallel data fetches for the same
EC, and too much back and forth between the CloudStore and the
ExtendedCloudProvider whenever a Cloud would get updated with
new tokens after they would get refreshed.
I fixed and changed a number of things. Here's a list of the most
prominent issues I addressed:
- addEventListener() in Cloud and EC was immediately calling the event
handler instead of adding it to the list of handlers.
- Cloud didn't have enough events. Just having the one DATA_UPDATED
event for all property changes was resulting in the EC using that
Cloud to get notified (and trigger a data fetch) much too often.
The EC only needs to fetch new data if the Cloud's sync-related
properties …
=> Optimize ExtendedCloud data fetches, fix bugs

src/common/ExtendedCloud.js, src/renderer/components/EnhancedTable/AdditionalInfoRows.js, src/renderer/components/EnhancedTable/EnhancedTableRow.js, src/renderer/components/GlobalPage/SynchronizeBlock.js, src/renderer/store/Namespace.js, test/mocks/mockExtCloud.js
We have a Namespace, and a Cluster class, yet `ExtendedCloud.namespaces`
was a list of anonymous objects with properties.
This moves it to being a list of Namespace objects using the existing
Namespace class, adding necessary properties to the class for clusters,
credentials, and SSH keys.
We're currently missing classes for Credentials and SSH keys. We'll need
to add those in a future PR. I will create a ticket for that. We should
propagate the use of raw API objects throughout the code.
This also changes the ExtendedCloud to always fetch ALL namespaces instead
of just the synced ones since we need to know what all exists at all times,
and adds a convenience `syncedNamespaces` getter that filters that list
to just what the Cloud is configured to sync for purposes of UI display
and …
=> Use existing Namespace class in ExtededCloud instead of anonymous object

src/common/Cloud.js, src/common/ExtendedCloud.js, src/renderer/auth/authUtil.js, src/renderer/components/EnhancedTable/EnhancedTableRow.js, src/strings.ts
I noticed that we ended-up with 2 ways of determining if a Cloud is
"connected" (which will lead to bugs down the line), and also an
incorrect notion of what "connected" means.
Now, we have a single way, `Cloud.status`, and a helper with
`Cloud.connected` (a boolean getter instead of a function, which
is true if status === CONNECTED, false otherwise, for cases where
the binary state is all we care about). Both properties are now
derived from the same set of logic in the `Cloud.status` getter,
so they won't diverge.
Also, "connected" really means the Cloud has all the necessary info
in order to make an API request. Without the `config` loaded, we're
technically not connected yet. So now, if we have everything except
the config, we consider this "connecting" because we have tokens,
but we …
=> Consolidate Cloud.isConnected() and Cloud.status, fix connected notion

.eslintrc.js, src/catalog/CredentialEntity.ts, src/catalog/ProxyEntity.ts, src/catalog/SshKeyEntity.ts, src/renderer/store/ProviderStore.js
So far, Prettier doesn't style class members in any specific way,
so this won't conflict with Prettier styling.
=> Add lint rule for class member styling

src/renderer/components/EnhancedTable/EnhancedTableRow.js, src/strings.ts
Added project list from `extendedCloud.cloud.syncNamespaces` instead of `extendedCloud.namespaces`, because in case we connected not all list of project, we still saw full list of project to related cloud.
=> Added correct project to confirm message

src/api/apiConstants.js, src/api/apiUtil.js, src/api/clients/KubernetesClient.js, src/api/clients/KubernetesEntityClient.js, src/api/types/ApiObject.js, src/api/types/Cluster.js, src/api/types/Credential.js, src/api/types/License.js, src/api/types/Namespace.js, src/api/types/Proxy.js, src/api/types/SshKey.js, src/common/Cloud.js, src/common/ExtendedCloud.js, src/main/IpcMain.js, src/renderer/components/ClusterPage/ClusterView.js, src/renderer/components/EnhancedTable/AdditionalInfoRows.js, src/renderer/components/EnhancedTable/EnhancedTableRow.js, src/renderer/components/GlobalPage/AddCloudInstance.js, src/renderer/components/GlobalPage/SyncView.js, src/renderer/components/GlobalPage/SynchronizeBlock.js, src/renderer/components/hooks/useCheckboxes.js, src/store/ClusterStore.js, src/strings.ts, src/typesets.js, src/util/mergeRtvShapes.js, test/mocks/mockExtCloud.js
The bulk of this change centers around the following:
- Establish the minimum RTV typesets for our expectations for
each entity type retrieved from the API.
- Convert `ExtendedCloud.fetchData()` to a "best-try" process
where we log errors and disregard entities instead of stopping
the fetch and trying to have an error message. This is in part
to greatly simplify the fetch, but also to deal with MCC
disabled components and user permissions that lead to 403
"access denied" responses when fetching certain entities. If at
all possible, we don't want to have to replicate this entire
system from MCC into the extension, so by simply being ready
to encounter 403s and ignore them (e.g. for BareMetal features
typically disabled), my hope is to skirt the issue.
- Rename a few key properties that …
=> Fetch all entity types from ExtendedCloud (and more)

src/common/Cloud.js, src/common/ExtendedCloud.js, src/renderer/components/EnhancedTable/EnhancedTable.js, src/renderer/components/EnhancedTable/EnhancedTableRow.js, src/renderer/components/EnhancedTable/TableRowListenerWrapper.js, src/renderer/components/EnhancedTable/tableUtil.js, src/renderer/components/GlobalPage/SyncView.js, src/renderer/components/GlobalPage/SynchronizeBlock.js, src/renderer/components/TriStateCheckbox/TriStateCheckbox.js, src/renderer/components/hooks/useCheckboxes.js, src/strings.ts, test/mocks/mockExtCloud.js
[Link to the ticket](https://mirantis.jira.com/browse/PRODX-21945)
Main changes: 
- Added 'Synchronize future projects' checkboxes for `syncAll` bool in SynchronizeBlock and in SelectiveSync Table
- Added `Cloud.ignoredNamespaces` where we store all unchecked projects
- Added logic to ExtendedCloud, which updates `Cloud.ignoredNamespaces`  and `Cloud.syncedNamespaces` in it got new project. Depending on `syncAll` we're choosing where to move new project ignored or synced
- Fixed issue when SelectiveSync table isn't updated after new data come (eg when Cloud disconnected=> we reconnect it and go to SelectiveSync view before EC.dataFetch is finished)
=> PRODX-21945 Fixed Selective sync UX issues

src/api/apiUtil.js, src/api/types/Credential.js
[Link to the ticket](https://mirantis.jira.com/browse/PRODX-22081)
- Used Buffer instead of `atob` for Node.js env
- Added one more Credential kind to the validation list
=> PRODX-22081 Updated extractJwtPayload and add missed Credential type

package.json, src/api/apiUtil.js, src/api/clients/ApiClient.js, src/api/types/ApiObject.js, src/api/types/Cluster.js, src/catalog/catalogEntities.js, src/catalog/catalogEntityTypes.ts, src/common/Cloud.js, src/common/DataCloud.js, src/constants.js, src/main/IpcMain.js, src/main/SyncManager.js, src/main/main.ts, src/renderer/catalogEntityDetails.tsx, src/renderer/components/EnhancedTable/EnhancedTableRow.js, src/renderer/components/EnhancedTable/TableRowListenerWrapper.js, src/renderer/components/GlobalPage/AddCloudInstance.js, src/renderer/store/DataCloudProvider.js, src/store/CloudStore.js, src/strings.ts, src/util/templates.js, yarn.lock
This commit adds cluster syncing to the SyncManager. It doesn't
store anything yet in the SyncStore, so it recreates the cluster
objects every time a DataCloud fetches new data.
It uses the `kubelogin` k8s plugin to allow Lens to connect to the
cluster, pushing cluster-specifi token generation to the point
where the cluster is opened in Lens so that the SyncManager doesn't
have to make SSO requests to generate those tokens, which would
require opening the user's default browser (UX would be very bad).
Also:
- Fixed bug in ApiClient.request() that was not letting the caller
specify the method to use to decode the body (so far, it was just
working as a fluke that all requests were 'json', which was the
default).
- For properties that are URLs, add custom validator to typesets
to make sure …
=> [PRODX-22267][PRODX-20046] Sync clusters down from MCC instances

src/api/apiUtil.js, src/api/clients/KubernetesClient.js, src/api/clients/ResourceClient.js, src/api/types/Cluster.js, src/api/types/Credential.js, src/api/types/License.js, src/api/types/Proxy.js, src/api/types/Resource.js, src/api/types/SshKey.js, src/catalog/catalogEntities.js, src/catalog/catalogEntityTypes.ts, src/common/Cloud.js, src/main/SyncManager.js, src/renderer/components/GlobalPage/SyncView.js, src/renderer/store/DataCloudProvider.js, src/store/SyncStore.js, src/util/logger.js
The SM is now much smarter than it was before because it leverages
the Kubernetes-provided `resourceVersion` as a way to detect if
a resource has changed since the last time it was synced.
The result is that only Catalog entities that are older than their
related resource get updated. Everything else that hasn't changed
just gets skipped. That greatly reduces churn.
Also:
- Deletes are now supported, cleaning-up unused kubeconfig files
(deletes meaning a namespace is no longer synced, or a Cloud
is removed).
- Fixed bug where we'd get an empty screen with a spinner at the
top/left right after adding a new (first) Cloud.
- Fixed bug where a removed Cloud would remain in the SyncView after
being removed.
=> [PRODX-22269] SyncManager efficient updates

src/renderer/renderer.tsx, src/renderer/topBar.tsx
UPD: Added new screenshots with dark/light versions
=> [PRODX-22248]: Replaced status bar button with top bar button to view extension page

src/api/apiConstants.js, src/api/clients/KubernetesClient.js, src/api/clients/ResourceClient.js, src/api/types/Cluster.js, src/api/types/Credential.js, src/api/types/License.js, src/api/types/Machine.js, src/api/types/Namespace.js, src/api/types/Node.js, src/api/types/Proxy.js, src/api/types/Resource.js, src/api/types/SshKey.js, src/catalog/CredentialEntity.ts, src/catalog/LicenseEntity.ts, src/catalog/ProxyEntity.ts, src/catalog/SshKeyEntity.ts, src/catalog/catalogEntities.js, src/common/DataCloud.js, src/main/SyncManager.js, src/renderer/catalogEntityDetails.tsx, src/strings.ts, src/util/netUtil.js, test/mocks/mockEntityModels.js, test/mocks/mockExtCloud.js
Relates other resources (SSH keys, credentials, proxies, licenses, machines)
to the clusters that use them.
Fetches all machines in all synced namespaces so that we can determine
a cluster's master and worker node counts, as well as it license
(since RHEL licenses are related to OpenStack cluster machines, not
the clusters themselves).
Adds a new `apiStatus` property to the Cluster Entity Model which
will provide a value for the "MCC Status" field in "View Details".
This is determined via "status conditions" on the cluster.
Also updates labels like this:
- Renames the much too long "managementCluster" label to "mgmt-cluster".
- Renames "sshKey" label to "ssh-key" as kebabcase seems more standard
for label/tag names.
- Adds new "is-mgmt-cluster=true" label to all mgmt clusters.
- All …
=> [PRODX-22307] Relate resources to clusters, add machines, add apiStatus

README.md, src/util/logger.js, src/util/netUtil.js
This enables support for self-signed certs (i.e. disables certificate
verification) when running Lens from the command line like this:
$ LEX_CC_UNSAFE_ALLOW_SELFSIGNED_CERTS=1 /path/to/Lens/exe.
=> [PRODX-22722] Add LEX_CC_UNSAFE_ALLOW_SELFSIGNED_CERTS cmd line switch

src/api/types/Cluster.js, src/common/DataCloud.js, src/main/SyncManager.js, src/store/CloudStore.js, src/store/SyncStore.js
The result before the fix was that all entities related to the still-
disconnected Cloud would get removed, when they should remain until
the Cloud is reconnected and synced, or removed outright.
The result after the fix is that only the entities and models related
to the Cloud being updated are touched in the Catalog and SyncStore.
All others are left alone. So the items for the still-disconnected
Cloud remain untouched.
=> [PRODX-22753] Fix bug when 2 clouds, disconnected, and connect just 1

src/api/apiUtil.js, src/api/types/Namespace.js, src/common/Cloud.js, src/common/DataCloud.js, src/common/EventDispatcher.js, src/main/SyncManager.js, src/renderer/store/DataCloudProvider.js, src/store/CloudStore.js
SyncManager now only fetches synced namespace metadata instead of
fetching metadata for ALL namespaces in ALL mgmt clusters.
Also, DataCloud, when in preview mode, doesn't create new instances
of Clusters, Credentials, and SshKeys. It just creates dummy objects
and then the Namespace class has setters for count properties which
are set instead of its typical array properties.
So now, DataCloudProvider always provides __preview__ instances
of DataClouds, while SyncManager always uses full instances.
This isn't enough, though, more to follow.
And the endless loop issue isn't fixed. Some `// TODO[PRODX-22830]`
comments remain in the code where I added additional logging in
hopes that, when it happens again (not sure what triggers it either),
we have more information to look at. And it's …
=> [PRODX-22830] Fetch optimization: Only fetch synced ns in SyncManager

src/renderer/components/EnhancedTable/AdditionalInfoRows.js, src/strings.ts
@stefcameron Should we show row for entity count if `count === 0` ?
=> [PRODX-23053]: added proxies and licenses counts for synced namespaced

package.json, src/api/apiConstants.js, src/api/clients/KubernetesClient.js, src/api/clients/ResourceClient.js, src/api/types/Cluster.js, src/common/Cloud.js, src/common/DataCloud.js, src/common/EventDispatcher.js, src/main/SyncManager.js, src/store/CloudStore.js, src/strings.ts, src/util/netUtil.js, yarn.lock
The idea was to leverage Kube's watch API[^1] to make fetches more
efficient instead of just a dumb 5 minute poll, especially, perhaps,
when syncing with multiple Clouds.
Implementation is done, but STUCK on a hard-to-debug or figure-out
issue, as documented with `// TODO[PRODX-22469]` comments in
DataCloud.js and SyncManager.js
For now, DataCloud instance continue to use polling. Besides, apparently
Kube watches expire after 5 minutes and a full data fetch has to be
done again to get a new `resourceVersion` for the collection anyway,
so it may not be worth spending more time on this and just ripping it
out. Search for all the TODO comments to know what to rip out.
Aside from this:
- Fixed a bug with wrong event name "LOADING_CHANGE" -> "LOADED_CHANGE"
- Fixed a bug where …
=> [PRODX-22469] Implement Kube watch API support after full data fetch

.gitignore, CHANGELOG.md, package.json, src/util/templates.js, yarn.lock
Download, make executable, and package kubelogin binaries for
macOS (x64, arm64), linux (x64), and windows (x64).
Update kubeconfig template to execute the correct binary based on
current OS directly instead of through kubectl as a plugin (the
result is the same).
=> [PRODX-23155] Bundle kubelogin with the extension

src/api/apiUtil.js, src/api/types/Cluster.js, src/api/types/SshKey.js, src/common/Cloud.js, src/common/DataCloud.js, src/main/SyncManager.js, src/store/CloudStore.js, src/strings.ts
After letting Lens sit open for a while, I hit this corner case where
the refresh token expired and couldn't be renewed while fetching
namespaces, resulting in ignoring the error and processing the
data as though all namespaces had been removed.
That resulted in losing all sync settings and all items being removed
from the Catalog.
To make matters worse, I had 'sync all' enabled, so when I reconnected,
we immediately _discovered_ all these _new_ namespaces and auto-synced
all 70 of them... Not what I wanted, although it did work and was
fairly performant (proving some of the recent work to optimize
fetching has paid off).
So this PR fixes this corner case. I let Lens sit open for 6 hours
untouched and it was still connected and still syncing just fine
with these changes.
The resiliency …
=> [PRODX-22315] Make DataCloud fetching more resilient

src/api/apiConstants.js, src/catalog/catalogEntities.js, src/common/DataCloud.js
When discovering namespaces, ignore ones that still exist, but have
been terminated.
=> [PRODX-22315] Ignore terminated namespaces

src/api/types/Cluster.js, src/api/types/Credential.js, src/api/types/License.js, src/api/types/Machine.js, src/api/types/NamedResource.js, src/api/types/Node.js, src/api/types/Proxy.js, src/api/types/SshKey.js
This also fixes a bug where Cluster and Machine resources didn't include their
namespace name in their toString debug log output, completes the inheritance
chain, and simplifies/centralizes the code.
=> Add NamedResource base class for all namespaced resources

CHANGELOG.md, src/api/types/Cluster.js, src/catalog/catalogEntities.js, src/common/DataCloud.js, src/constants.js, src/renderer/catalogEntityDetails.tsx, src/strings.ts, test/mocks/mockExtCloud.js
StackLight URLs are only displayed if StackLight is enabled and
endpoints are available, and only the available endpoints are
displayed.
The MKE dashboard URL is always displayed since that is always
available.
All URLs are clickable and open in the user's default browser.
=> [PRODX-23850] Expose MKE and StackLight URLs in cluster details

CHANGELOG.md, src/common/DataCloud.js, src/constants.js, src/main/IpcMain.js, src/main/SyncManager.js, src/main/main.ts, src/renderer/IpcRenderer.js, src/renderer/components/GlobalPage/AddCloudInstance.js, src/renderer/renderer.tsx
Adds power suspend/resume and network offline/online detection.
Note that network offline/online detection is not 100% reliable since Lens could be running
in a VM with its network adapter configured to be "always connected", which would result
in false-negatives if the host loses network connectivity (i.e. host goes offline, and we think
we're still connected because we don't receive an "offline" event).
---
I also realized, that we can debug in console IpcMain events. We can see network statuses in console.
=> [PRODX-22916]: Added onSuspend and onResume events

__mocks__/@k8slens/extensions.js, src/renderer/components/__tests__/Loader.spec.js
I think I covered all UI, and we have no logic here, but I received only 75% coverage of `Branch` column.
UPD: now it covered 100%. Screen attached
=> [PRODX-24171]: added tests for Loader component

__mocks__/@k8slens/extensions.js, package.json, src/renderer/components/Wizard/Wizard.js, src/renderer/components/Wizard/WizardStep.js, src/renderer/components/Wizard/__tests__/Wizard.spec.js, src/renderer/components/Wizard/__tests__/WizardStep.spec.js, src/strings.ts, tools/tests/.eslintrc.js, tools/tests/testTools.js, yarn.lock
The Wizard is mostly modeled according to Lens' Preferences Panel,
but with additional control over the step list's functionality,
and back/next/finish buttons.
__NOTE:__ The preview is not for the Create Cluster work, it's just for what the Wizard looks like.
=> Add Wizard component for use with Create Cluster wizard

__mocks__/@k8slens/extensions.js, package.json, src/common/__mocks__/Cloud.js, src/constants.js, src/renderer/components/CreateClusterWizard/ClusterStep.js, src/renderer/components/CreateClusterWizard/CreateClusterWizard.js, src/renderer/components/CreateClusterWizard/EquinixProvider.js, src/renderer/components/CreateClusterWizard/GeneralStep.js, src/renderer/components/CreateClusterWizard/MonitorStep.js, src/renderer/components/CreateClusterWizard/NodeStep.js, src/renderer/components/CreateClusterWizard/ProviderStep.js, src/renderer/components/CreateClusterWizard/createClusterUtil.js, src/renderer/components/EnhancedTable/EnhancedTable.js, src/renderer/components/EnhancedTable/EnhancedTableRow.js, src/renderer/components/EnhancedTable/TableRowListenerWrapper.js, src/renderer/components/EnhancedTable/__tests__/EnhancedTable.spec.js, src/renderer/components/EnhancedTable/__tests__/EnhancedTableRow.spec.js, src/renderer/components/EnhancedTable/__tests__/TableRowListenerWrapper.spec.js, src/renderer/components/GlobalPage/ConnectionBlock.js, src/renderer/components/GlobalPage/SyncView.js, src/renderer/components/GlobalPage/__tests__/GlobalPage.spec.js, src/renderer/components/GlobalPage/__tests__/SyncView-contextMenus.spec.js, src/renderer/components/GlobalPage/__tests__/SyncView.spec.js, src/renderer/components/RequiredMark.js, src/renderer/store/CloudProvider.js, src/strings.ts, tools/tests/testTools.js, yarn.lock
Defines the steps with placeholders for content and establishes a few patterns
for how we will structure the code.
NOTE: For now, the 'Create cluster' item is only visible in dev builds.
This is so that we can easily work on the feature without making it available
if we need to publish an update, and so we don't need a feature branch.
Also relocates the cloud and namespace menu items from EnhancedTableRow to
the SyncView. EnhancedTableRow is just a component that's used by the view.
The view should be the owner of the menu items that get displayed, as well
as their handlers. In particular, the CreateClusterWizard, hence the change.
Also formally added lodash as a dependency. We were already using it, but
it wasn't declared. It must've been there as a downstream dependency of
babel-lodash. …
=> [PRODX-25977] Add basic structure for Create Cluster wizard

src/renderer/components/CreateClusterWizard/ClusterStep.js, src/renderer/components/CreateClusterWizard/CreateClusterWizard.js, src/renderer/components/CreateClusterWizard/EquinixProvider.js, src/renderer/components/CreateClusterWizard/GeneralStep.js, src/renderer/components/CreateClusterWizard/MonitorStep.js, src/renderer/components/CreateClusterWizard/NodeStep.js
This will help ensure that the data structure the wizard generates
is exactly as we expect it to be.
By using the `exactShapes` option in the verifications, we'll know
if a rogue property was added or removed somewhere in the code and
the data structure has inadvertently changed.
=> [PRODX-25977] Add RTV validation to wizard

CHANGELOG.md, src/renderer/catalogEntityDetails.js
Check if done, remove if not applicable:
=> [CCLEX-166]: Changed timestamp format in 'Synced at' and 'Created at' fields

CHANGELOG.md, README.md, src/constants.js, src/util/netUtil.js, src/util/templates.js
When setting `LEX_CC_UNSAFE_ALLOW_SELFSIGNED_CERTS=1` on the command line to run Lens, we disable TLS verification when making API requests, but we aren't disabling it when Lens attempts to access the cluster to generate a cluster token via the `kube-login` binary.
This fix will disable TLS verification in the kubeConfig also, if the command line flag is set.
Check if done, remove if not applicable:
=> [CCLEX-171] Skip TLS verification in kubeConfigs when requested

src/api/types/Cluster.js, src/renderer/catalogEntityDetails.js, src/strings.ts
The `lma` data of a cluster entity will be `null` if the cluster isn't configured with StackLight. The code needs to handle this case.
Also, now that we're not showing/hiding the LMA panel, it seems good to include an 'Enabled: Yes/No' field to indicate whether StackLight is configured on the cluster or not, since it might not be obvious just with the '--' values for URLs. For example, are all the URLs not available because SackLight is disabled, or because those services aren't available for some reason...?
- Already added with #1176
=> [CCLEX-183] Handle not having lma; show enabled state in details

CHANGELOG.md, src/api/types/Credential.js
This was due to in incorrect expectation for `status.ready` in the kube resource specically for BYO credentials. Other credential types have this object.
Check if done, remove if not applicable:
=> [CCLEX-184] Fix BYO credentials not visible in Catalog

package.json, src/api/apiConstants.js, src/api/clients/KubernetesClient.js, src/api/clients/ResourceClient.js, src/common/DataCloud.js, src/main/SyncManager.js, yarn.lock
It was added last April, but couldn't be enabled and tested because of an issue with Node and extracting the body of the watch payload:
> Disabling watches until a solution can be found to the behavior where a watch
> request's response comes back almost immediately as status 200, but then
> attempting to extract the body with `response.text()` in
> `netUtils.js#tryExtractBody()` NEVER resolves. It just hangs.
>
> I thought this might be similar to this issue: https://github.com/node-fetch/node-fetch/issues/665
> And solution (for node-fetch 2.x): https://github.com/node-fetch/node-fetch#custom-highwatermark
>
> But, alas, that didn't help at all. No clue what's going on. Works great in
> Postman, so clearly, the issue is with how we're handling these types of
> long-poll requests in …
=> [CCLEX-74] REMOVE kube watches implementation

.eslintrc.js, src/api/apiConstants.js, src/api/apiFetch.js, src/api/apiTypesets.js, src/api/apiUtil.js, src/api/clients/ResourceClient.js, src/api/types/Cluster.js, src/api/types/ClusterDeployment.js, src/api/types/ClusterUpgrade.js, src/api/types/MachineDeployment.js, src/api/types/MachineUpgrade.js, src/api/types/Namespace.js, src/api/types/Resource.js, src/api/types/ResourceEvent.js, src/api/types/ResourceUpdate.js, src/catalog/catalogEntities.js, src/common/CloudConfig.js, src/common/DataCloud.js, src/globals.d.ts, src/main/SyncManager.js, src/renderer/renderer.tsx, src/routes.ts, src/strings.ts, webpack.config.js
This adds an `updates` property on Cluster objects and cluster entities containing cluster/machine deployment/upgrade history, if available.
It also renames the 'Performance' tab to 'Updates' since we won't have a Performance tab anymore, but we're adding the Updates tab.
Since we need MCC v2.22 to get the new `stages[].status` field in `ClusterDeploymentStatus`, `ClusterUpgradeStatus`, `MachineDeploymentStatus`, and `MachineUpgradeStatus`, fetching updates is behind a new Webpack-enabled `FEAT_CLUSTER_PAGE_UPDATES_ENABLED` switch which can be set on the command line to opt in to seeing the Updates tab when running in Dev mode (or building Prod with the flag).
n/a (nothing new for the user, and no new data synced unless cluster page feature is enabled)
=> [CCLEX-186] Add cluster updates to API and cluster entities

CHANGELOG.md, src/renderer/topBarItems.js
Our own fix for https://github.com/lensapp/lens/issues/6658
Broken:
Fixed:
=> Fix broken extension top bar item layout after Lens upgrade

src/api/apiFetch.js, src/api/types/Cluster.js, src/api/types/MachineEvent.js, src/catalog/catalogEntities.js, src/common/DataCloud.js
Also renames `apiFetch.fetchClusterEvents()` and `apiFetch.fetchClusterUpdates()`
to be more generic since we're fetching cluster and machine events and updates.
n/a (feature not yet published)
=> [CCLEX-186] Add MachineEvent class, include machine events in cluster entities

src/api/__tests__/metricPromMock.js, src/api/apiUtil.js, src/api/clients/ApiClient.js, src/api/clients/AuthorizationClient.js, src/api/clients/KubernetesClient.js, src/api/clients/ResourceClient.js, src/api/metricApi.js, src/renderer/renderer.tsx, src/strings.ts, src/util/netUtil.js
Since we're blocked on PRODX-28459 in terms of accessing the Prometheus API on a given cluster (cloud), this commit includes a `./__tests__/metricPromMock.js` module that currently takes care of fulfilling Prometheus API requests made by the new metricApi.js module.
The metricApi.js module seeks to abstract the details of calling the Prometheus API by exposing high level functions like `getCpuMetrics()`, `getMemoryMetrics()`, and `getDiskMetrics()` which, internally, execute multiple Prometheus queries in order to gather the necessary data.
We should be able to build the Health panel based on this module and the fake data for now until we can get rid of the mock layer and reach Prometheus directly.
Here's some sample code that calls each of the methods and prints the results to the …
=> [CCLEX-178] Add metrics API module with mock API responses

.eslintrc.js, src/globals.d.ts, src/renderer/components/ClusterPage/Overview/ClusterOverviewView.js, src/renderer/components/ClusterPage/Overview/HealthPanel.js, tools/scripts/test/testConfigs.mjs, webpack.config.js
HealthPanel is empty, just a placeholder.
Set `FEAT_CLUSTER_PAGE_HEALTH_ENABLED=1` on the command line when using `yarn start` to build the extension for local testing.
n/a
=> [CCLEX-173] Add HealthPanel behind new FEAT_CLUSTER_PAGE_HEALTH_ENABLED flag

CHANGELOG.md, src/renderer/components/ClusterPage/Overview/SummaryPanel.js
Fix how cluster label values are listed in the
`Cluster page > MCC > Overview` panel.
Some contain lists of referenced objects like credentials and SSH keys, and these lists are now pretty-printed with spaces.
Before: 'foo,bar,baz'
After: 'foo, bar, baz'
=> [CCLEX-193] Fix display of cluster label list values

.eslintrc.js, CHANGELOG.md, src/common/Cloud.js, src/common/DataCloud.js, src/renderer/components/EnhancedTable/EnhancedTableRow.js, src/renderer/components/GlobalPage/AddCloudInstance.js, src/renderer/components/GlobalPage/ConnectionBlock.js, src/renderer/components/GlobalPage/__tests__/AddCloudInstance.spec.js, src/renderer/components/GlobalPage/__tests__/ConnectionBlock.spec.js, src/renderer/components/TriStateCheckbox/TriStateCheckbox.js, src/renderer/rendererUtil.js, src/strings.ts
When adding a new mgmt cluster, if a connection error occurs, we now parse it to see if it's a certificate error (self-signed certs), a connection error, or some other unknown error, and display the friendly error message in an error notification popup that sticks to the screen until the user manually dismisses it (instead of having it stay visible only for 1-2 seconds and always be a generic message).
When reconnecting a disconnected mgmt cluster, if there's a connection error, we now show a little error icon next to the "Disconnected" status, with a friendly, more helpful connection error message in a tooltip on hover over the error icon.
Also:
- Added better disabled state support to TriStateCheckbox
- Made sure that Connect button (when adding a new mgmt cluster) remains disabled if …
=> [CCLEX-194] Surface better connection error messages

CHANGELOG.md, README.md, __mocks__/@k8slens/extensions.js, src/renderer/components/GlobalPage/ConnectionBlock.js, src/renderer/components/GlobalPage/SyncView.js, src/renderer/components/GlobalPage/TrustHostModal.js, src/renderer/components/InlineNotice.js, src/renderer/components/Modal/Modal.js, src/renderer/components/TriStateCheckbox/TriStateCheckbox.js, src/renderer/components/Wizard/Wizard.js, src/renderer/rendererUtil.js, src/renderer/store/CloudProvider.js, src/strings.ts, src/util/netUtil.js
Since the `LEX_CC_UNSAFE_ALLOW_SELFSIGNED_CERTS` flag has been removed, but users will still be using it after installing v5.5.0, if the flag is set, and the user is syncing at least one untrusted cloud with a secure (https) connection, a special dialog will be displayed showing a checkbox per secure, untrusted cloud, allowing the user an opportunity to trust the clouds that need to be trusted.
This dialog is only shown once per Lens session.
Also added new Modal component, since the Lens Dialog component is not designed to be used on its own, and Lens doesn't provide a generic dialog component like that which was needed.
Also updated the 'Add mgmt cluster' view to disable the 'trust this host' option when the URL is not https, and restricted the mgmt cluster URL to http or https only …
=> [CCLEX-179] Add 'Configure trusted hosts' migration dialog

__mocks__/@k8slens/extensions.js, src/main/SyncManager.js, src/main/main.ts, src/renderer/components/GlobalSyncPage/EnhancedTable/__tests__/EnhancedTable.spec.js, src/renderer/components/GlobalSyncPage/EnhancedTable/__tests__/EnhancedTableRow.spec.js, src/renderer/components/GlobalSyncPage/EnhancedTable/__tests__/TableRowListenerWrapper.spec.js, src/renderer/components/GlobalSyncPage/__tests__/AddCloudInstance.spec.js, src/renderer/components/GlobalSyncPage/__tests__/ConnectionBlock.spec.js, src/renderer/components/GlobalSyncPage/__tests__/GlobalSyncPage.spec.js, src/renderer/components/GlobalSyncPage/__tests__/SyncView-contextMenus.spec.js, src/renderer/components/GlobalSyncPage/__tests__/SyncView.spec.js, src/renderer/components/GlobalSyncPage/__tests__/SynchronizeBlock.spec.js, src/renderer/renderer.tsx, src/renderer/store/CloudProvider.js, src/renderer/store/__tests__/CloudProvider.spec.js, src/store/CloudStore.js, src/store/SyncStore.js
- https://github.com/lensapp/lens/blob/master/packages/core/src/extensions/extension-store.ts
- https://github.com/lensapp/lens/pull/6690 ("Make base store non Singleton")
- https://github.com/lensapp/lens/issues/4573 ("Elimination of global shared state")
The `createInstance()` and `getInstance()` methods had been deprecated in the Lens Extensions API, so they have been eliminated from our code base also. But we're still using "global shared state" Cloud and Sync store instances. It's just that Lens isn't the one creating and holding the instance anymore, we are.
n/a
=> ExtensionStore is no longer a Singleton in Lens since some 6.4.x release

.eslintrc.js, src/api/apiConstants.js, src/api/apiUtil.js, src/api/metricApi.js, src/common/Cloud.js, src/common/DataCloud.js, src/common/__mocks__/Cloud.js, src/constants.js, src/globals.d.ts, src/renderer/components/ClusterPage/Overview/ClusterOverviewView.js, src/renderer/components/ClusterPage/Overview/HealthPanel.js, src/renderer/renderer.tsx, src/renderer/rendererUtil.js, src/store/CloudStore.js, src/strings.ts, src/util/netUtil.js, tools/scripts/test/testConfigs.mjs, webpack.config.js
Basically, even after PRODX-28459 and MCC v2.23 with the fix, we still have 2 problems:
1. The Prometheus host uses a self-signed cert which requires the host to be trusted, which requires removing the Cloud entirely and re-adding it with "trust this host" enabled... Bad UX.
2. If the host is trusted, then we still hit a `401 Unauthorized` response from the Prometheus endpoint in spite of using brand new, certainly not expired, tokens.
Nonetheless, I was still able to move things forward a bit:
- Webpack command line switch is replaced with a soft version check, which remains disabled for now (so the Health panel will not show up unless `const showHealth = false` is set to `true` in ClusterOverview.js
- New bits and bobs added to enable the MCC version check later on (see new `// …
=> [CCLEX-178] Attempt to make this work, but still blocked
