CHANGELOG.md
src/cc/Login.js
src/cc/PreferencesPanel.js
src/cc/View.js
src/cc/store/AuthProvider.js
src/cc/store/ClusterActionsProvider.js
src/cc/store/ClustersProvider.js
src/cc/store/ConfigProvider.js
src/cc/store/ExtStateProvider.js
src/cc/store/PreferencesStore.js
src/cc/store/ProviderStore.js
src/main.ts
src/renderer.tsx

[#13] Use Lens store for preferences

---

src/renderer/components/GlobalPage/GlobalPage.tsx
src/renderer/components/GlobalPage/SyncView.js
src/renderer/eventBus.ts
src/renderer/renderer.tsx
src/renderer/store/ClusterActionsProvider.js
src/strings.ts

Changed logic at `renderer.tsx` related to handleProtocolActivateCluster
Instead of redirect to GlobalPage (SyncView) we navigate to the cluster

PRODX-20521 Update handleProtocolActivateCluster

---

src/common/Cloud.js
src/constants.js
src/main/main.ts
src/renderer/auth/Cloud.js
src/renderer/auth/clients/AuthClient.js
src/renderer/components/GlobalPage/ConnectionBlock.js
src/renderer/components/GlobalPage/Login.js
src/renderer/components/GlobalPage/SyncView.js
src/renderer/eventBus.ts
src/renderer/hooks/useClusterLoader.js
src/renderer/hooks/useClusterLoadingState.js
src/renderer/renderer.tsx
src/renderer/store/ClusterActionsProvider.js
src/renderer/store/ExtStateProvider.js
src/store/CloudStore.js
src/util/ssoUtil.js

Added and connected CouldStore through new ConnectBlock click. This is not a final version, rather a checkpoint.

PRODX-19642 Added CloudStore

---

src/common/ExtendedCloud.js
src/renderer/components/GlobalPage/AddCloudInstance.js
src/renderer/components/GlobalPage/ConnectionBlock.js
src/strings.ts

This is a WIP version. Recommendations are welcomed

PRODS-20985 Create ExtendedCloud

---

src/renderer/components/EnhancedTable/EnhancedTable.js
src/renderer/components/EnhancedTable/EnhancedTableHead.js
src/renderer/components/GlobalPage/SynchronizeBlock.js

This PR is identical to #695 except is has a clean git history.

[PRODX-21380] Adding sort feature to table

---

src/common/Cloud.js
src/common/ExtendedCloud.js
src/renderer/components/GlobalPage/Login.js
src/renderer/hooks/useClusterLoader.js
src/renderer/store/ExtendedCloudProvider.js

WIP version ExtendedCloudProvider
- load cloudStore.clouds - check them and create extendedClouds
- update extendedClouds when cloudStore.clouds are changed (comparison based on `token`)
- Update ExternalCloud additional data (namespaces, etc) each 5 min
- Listen changes in ExternalCloud.namespaces

PRODX-21180 Added ExtendedCloudProvider.js

---

src/renderer/components/GlobalPage/ConnectionBlock.js
src/strings.ts

PRODX-21533: Added Inout validations to ConnectionBlock.js

---

src/renderer/components/EnhancedTable/EnhancedTableRow.js
src/strings.ts

PRODX-21452: Added Context menu to rows

---

src/renderer/components/TriStateCheckbox/TriStateCheckbox.js

[PRODX-21659]: fixed checkbox icon font size to make it integer

---

src/common/Cloud.js
src/common/EventDispatcher.js
src/common/ExtendedCloud.js

They had the same implementation of the event dispatching logic.
Only seemed obvious this should be in a common base class.

Cloud and ExtendedCloud extend from new EventDispatcher base class

---

src/renderer/components/EnhancedTable/EnhancedTableRow.js

Fire `extCloud.cloud.connect()` on 'reconnect' click

PRODX-21649: Added reconnect logic

---

src/common/ExtendedCloud.js
src/renderer/components/EnhancedTable/AdditionalInfoRows.js
src/renderer/components/GlobalPage/SynchronizeBlock.js
src/renderer/store/ApiObject.js
src/renderer/store/Cluster.js
src/renderer/store/Credential.js
src/renderer/store/License.js
src/renderer/store/Namespace.js
src/renderer/store/Proxy.js
src/renderer/store/SshKey.js
test/mocks/mockExtCloud.js

Added  next classes: 
- `SshKey`
- `Proxy`
- `License`
- `Credential`
Updated `Cluster` and `Namespace` classes according to [the ticket description  ](https://mirantis.jira.com/browse/PRODX-21692)
Also instead of `namespace` name (string type) from API call, we store `Namespace` in those Classes mentioned above

PRODX-21692 Added more Classes

---

src/renderer/components/EnhancedTable/EnhancedTableRow.js
src/strings.ts

[PRODX-21648]: added remove cloud logic

---

src/renderer/components/GlobalPage/AddCloudInstance.js
src/renderer/components/GlobalPage/ConnectionBlock.js
src/strings.ts

[PRODX-21534]: Added spinner to AddCloudInstance component

---

src/renderer/components/GlobalPage/SynchronizeBlock.js
src/strings.ts

Show message for MMG clusters without projects

---

src/renderer/components/EnhancedTable/EnhancedTableRow.js
src/renderer/store/Credential.js
src/strings.ts

Since our Spinner component doesn't suite to the table, I added one more status 'Updating' during fetchingData event. 
In my opinion, spinner or animation would be better, but it's need more work from Lens/designers side. Open to proposals
Also we hide accordion arrow til we get namespaces (in first time)

PRODX-21857 Added one more status for EC.fetchingData

---

src/renderer/components/EnhancedTable/EnhancedTableRow.js

Same state for `Sync now` button in case, when `Status` is `Disconnected`

[PRODX-21863]: added disabled button state to cloud context menu

---

src/common/Cloud.js
src/common/ExtendedCloud.js
src/renderer/components/EnhancedTable/EnhancedTable.js
src/renderer/components/EnhancedTable/EnhancedTableRow.js
src/renderer/components/GlobalPage/SyncView.js
src/renderer/components/GlobalPage/SynchronizeBlock.js
src/renderer/components/hooks/useCheckboxes.js

[Link to the ticket](https://mirantis.jira.com/browse/PRODX-21766)
Now we can Selective Sync mode is working. We can select namespaces and update clouds

PRODX-21766 Added Selective sync logic

---

src/common/ExtendedCloud.js

Fixed EC ignoredNamespaces

---

src/renderer/components/GlobalPage/SyncView.js

[PRODX-22021]: Fix button in selective sync mode

---

src/api/types/Cluster.js
src/api/types/Machine.js
src/common/DataCloud.js

Now, if a machine in a cluster has a license, it'll surface in the
cluster, and the cluster will get a 'license' label with its name.

[PRODX-22307] Relate licenses to Machines and Clusters

---

src/api/types/Cluster.js
src/catalog/catalogEntities.js
src/renderer/catalogEntityDetails.tsx
src/renderer/renderer.tsx
src/strings.ts

- Added additional informations
- Added "Open in browser" option
Please check attached:
First screenshot - non Management cluster panel
Second screenshot - Management cluster panel

[PRODX-22031]: "Clusters" additional information

---

src/renderer/components/GlobalPage/SyncView.js

Making changes to the selection of one cloud out of 2 would result
in changes being ignored in one cloud or the other.

Fix bugs in SyncView selective sync mode

---

src/common/DataCloud.js
src/renderer/components/EnhancedTable/EnhancedTable.js
src/renderer/components/EnhancedTable/EnhancedTableHead.js
src/renderer/components/EnhancedTable/tableUtil.js

- Fixed issue, when sorting was working only with `URL` column
- Fixed visual behaviour of sorting arrow

[PRODX-22754]: fixed bug with table sorting

---

src/api/types/Cluster.js
src/catalog/catalogEntities.js
src/renderer/catalogEntityDetails.tsx
src/strings.ts

[PRODX-23054]: Removed child count from management cluster details view

---

src/renderer/components/TriStateCheckbox/TriStateCheckbox.js
src/renderer/components/TriStateCheckbox/__tests__/TriStateCheckbox.spec.js

[PRODX-24176]: added tests for TriStateCheckbox component

---

__mocks__/@k8slens/extensions.js
src/renderer/components/GlobalPage/WelcomeView.js
src/renderer/components/GlobalPage/__tests__/WelcomeView.spec.js
src/strings.ts

[PRODX-24170]: added tests for WelcomeView component

---

src/renderer/components/__tests__/ErrorPanel.spec.js
src/renderer/components/__tests__/InfoPanel.spec.js

[PRODX-24171]: Added tests for ErrorPanel and InfoPanel components

---

src/renderer/components/__tests__/styles.spec.js

[PRODX-24171]: added tests for styles

---

__mocks__/@k8slens/extensions.js
src/renderer/components/__tests__/InlineNotice.spec.js

[PRODX-24171]: added tests for InlineNotice component

---

.github/workflows/ci.yml
__mocks__/@k8slens/extensions.js
src/__tests__/cloudTestUtil.js
src/renderer/components/EnhancedTable/AdditionalInfoRows.js
src/renderer/components/EnhancedTable/__tests__/AdditionalInfoRows.spec.js
src/renderer/components/__tests__/ContainerCloudIcon.spec.js

There is 100% coverage, but need to fix `console.error` before merging
UPD: error fixed

[PRODX-24169]: added tests to AdditionalInfoRows component

---

src/renderer/components/EnhancedTable/__tests__/tableUtil.spec.js
src/renderer/components/EnhancedTable/tableUtil.js

[PRODX-24169]: added tests for tableUtil

---

__mocks__/@k8slens/extensions.js
src/renderer/components/GlobalPage/__tests__/SyncView.spec.js

Reminder: Need to cover `handleAddCloud()` method
UPD: this block wasn't covered after submitting. Should we cover it or we are good with this coverage percentage?

[PRODX-24170]: added tests for SyncView component

---

CHANGELOG.md
src/renderer/components/GlobalPage/SynchronizeBlock.js
src/renderer/components/GlobalPage/__tests__/SynchronizeBlock.spec.js

[PRODX-24170]: added tests to SynchronizeBlock component

---

__mocks__/@k8slens/extensions.js
src/renderer/components/GlobalPage/__tests__/ConnectionBlock.spec.js

[PRODX-24170]: added tests for ConnectionBlock component

---

package.json
src/api/__tests__/apiUtil.spec.js
tools/tests/jestSetup.js
yarn.lock

**Update:**
Covered 85+% in each block.

[CCLEX-65]: added tests for apiUtil

---

CHANGELOG.md
src/renderer/catalogEntityDetails.js

[CCLEX-183]: Show '--' instead of the URL if StackLight is disabled

---

CHANGELOG.md
src/renderer/components/GlobalPage/ConnectionBlock.js

[CCLEX-182]: Update mgmt cluster URL after "Connect" button clicking

---

CHANGELOG.md
src/renderer/catalogEntityDetails.js
src/renderer/components/ClusterPage/Details/GeneralInformation.js
src/renderer/components/ClusterPage/Overview/SummaryPanel.js
src/strings.ts

[CCLEX-187]: Added Namespace to entity details view and Cluster details page

---

src/api/apiConstants.js
src/renderer/components/ClusterPage/Events/EventsPanel.js
src/renderer/components/ClusterPage/History/ClusterHistoryView.js
src/renderer/components/ClusterPage/History/HistoryPanel.js
src/renderer/components/ClusterPage/ItemsTable.js
src/renderer/components/ClusterPage/clusterPageComponents.js
src/renderer/components/ClusterPage/clusterPageUtil.js
src/renderer/components/ClusterPage/useCloudSync.js
src/renderer/renderer.tsx
src/strings.ts

`EventsTable` and `HistoryTable` components were moved to re-usable `ItemsTable` component. Also did some changes in `EventsPanel` to meet `ItemsTable` structure.

[CCLEX-185]: History panel

---

.github/workflows/ci.yml
src/renderer/renderer.tsx

Prepare for Lens v6.4.0 release changes
